### ISSUE TITLE
android do not use

### ISSUE THREAD

**Issue by Caij** [dnbn/submerge#2]
java framework class missing。 eg : PropertyDescriptor

**Comment by dnbn** [comment]
Looks like java.beans package is not complete on android.

I suggest you to include [openbeans](https://github.com/melix/openbeans) and [submerge-api](https://github.com/dnbn/submerge/tree/master/submerge-api) as modules in your project.
Then replace reference to java.beans.PropertyDescriptor by com.googlecode.openbeans.PropertyDescriptor in the class com.github.dnbn.submerge.api.parse.AssParser

This should do the trick.

**Comment by Caij** [comment]
thanks
